### ISSUE TITLE
Next features

### ISSUE THREAD

**Issue by xzab** [ph1p/figma-chat#1]
First I just have to say this is AWESOME and thank you for making this plugin!  The 2 biggest pieces I noticed (and saw one on your to-do list) is notifications (biggest) and the ability to dock it or minimize it somehow but have it still accessible.  Would love for it to be integrated into the UI a little more when I don't want it floating.  

Thanks again!

**Comment by ph1p** [comment]
Hi @xzab :) 
Sorry for the delay. 
> .... is notifications (biggest) and ....
- I have already integrated the notifications. It's not published yet because I want to add more settings and as you already noticed, the possibility to minimize it.

Thank you for reaching out! :)
I'm working on it!

I'll write in here when it's done.

**Comment by xzab** [comment]
Awesome, thanks for the reply! Can't wait. Oh I also noticed when another plug-in runs, specifically the "to-do list" plug-in it takes over the chat window. Not sure if this is a problem with just these two plug-ins or possibly others?

**Comment by ph1p** [comment]
Hi @xzab ! I've updated the plugin and now you can minimize and hide it! I also integrated the notifications. Hope you like it. I'm not the best in designing things and try to rethink some of my "design" decisions ^^

Next thing todo: Make intelligent notifications (on unfocus or on minimize)

**Comment by ph1p** [comment]
I close this issue, because I think it's resolved (:
Today I'll publish a complete restructured version with some design changes and automatic selection detection.
