### ISSUE TITLE
ability to type ã õ á é etc characters 

### ISSUE THREAD

**Issue by jorgemartins** [ph1p/figma-chat#3]
![screencast+2020-03-13+01-31-31](https://user-images.githubusercontent.com/1323193/76581206-88d42f80-64ca-11ea-92c1-565c9180cd2d.gif)

currently, like it can be seen on the gif, I can't create _á_ as it is assuming `~` as a single character input

**Comment by ph1p** [comment]
Hi @jorgemartins . I'll look at it as soon as possible. Thank you for reporting it

**Comment by ph1p** [comment]
Fixed! You should now be able to type as you wish (:

**Comment by jorgemartins** [comment]
perfect fix. Thanks for the plugin and the fix too 🙏

**Comment by ph1p** [comment]
You're welcome (:
