### ISSUE TITLE
New feature - Sound notification

### ISSUE THREAD

**Issue by gbrielfnb** [ph1p/figma-chat#5]
Hey man! Is there any possibility to habilitate a sound notification? Sometimes i am not using figma so i cant know if there is any message and if possible to turn off notification! By the way... Thanks by creating this awesome plugin xD

**Comment by ph1p** [comment]
Hi (: I'll see if sound works in the plugin window. Disabling notifications is a good idea. I'll work on it and release it as soon as possible. Thank you!

**Comment by ph1p** [comment]
@gbrielfnb Finished it! It's now live! Hope you like it
