### ISSUE TITLE
Select object in figma project!

### ISSUE THREAD

**Issue by Mateusresende** [ph1p/figma-chat#6]
Hello, very good your initiative.

I had difficulty with selecting the objects.
It worked. But then, how do I select others? It seems like a bug and we don't know how to deselect and select others.

Congratulations!!
Really enjoyed!

**Comment by Mateusresende** [comment]
When the ADD current selection (1 element) window appears

And how do I cancel?
And when I select another one (it doesn't modify, update) for other selected elements

**Comment by ph1p** [comment]
Hi @Mateusresende !
I've recorded a small video for you. This is how the selections should work, maybe you have discovered an error. I'm always open to suggestions for improvement :)

![selection](https://user-images.githubusercontent.com/15351728/79551975-b2b8dd00-809a-11ea-957a-dd881334c6ac.gif)
