### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by GreenEggsandHam19** [ph1p/figma-chat#8]
I've used the default server and also tried other servers, but I keep getting the same issue saying "Connection failed".

**Comment by ph1p** [comment]
Hi @GreenEggsandHam19 

Thanks for reporting :) Could you please give me some small informations like: 
- What do you use, web figma or the application?
- Whats you OS? mac, windows or linux?

Also try to click on the small "(reset)" next to the Server-URL-Label.

**Comment by GreenEggsandHam19** [comment]
Using Figma web app and on Windows 10. 

I've tried the reset button but it doesn't seem to work either.

**Comment by ph1p** [comment]
All righty! I will try to reproduce the error. It would be really helpful if you create a public figma file where the error occurs and post the link here. Thank you :)

**Comment by GreenEggsandHam19** [comment]
https://www.figma.com/file/KaVqgnvZFVEXS3UrZiTdpL/Testing-figma-chat?node-id=0%3A1 Not sure if this will work?

**Comment by ph1p** [comment]
All good! Thank you :)

**Comment by ph1p** [comment]
Hi @GreenEggsandHam19 sorry for the small delay.
I tried to reproduce the connection problem, but I can't :/

So I have some more questions:
- Can you access https://figma-chat.ph1p.dev directly?
- Whats your Browser + Version?

**Comment by ph1p** [comment]
I would close this for now due to inactivity. Feel free to reopen it, if you have more information :)

**Comment by ZiyanKS** [comment]
Reopening this Issue.
Unable to connect to the server. I'm trying to connect from the default server, but I'm getting the error "connection failed 🙈"
